language: node_js
node_js:
  - 10
script:
  - npm run build
  - npm test
deploy:
  provider: pages
  verbose: true
  skip_cleanup: true
  github-token: $GITHUB_TOKEN # Set in the settings page of your repository, as a secure variable
  keep-history: true
  on:
    branch: master
