services: 
  - docker

before_install:
  - npm install -g cypress

script:
  - docker-compose -f docker-compose.prod.yml up -d 
  - cypress run .

env: TZ=America/Chicago
#deploy:
#  provider: pages
#  verbose: true
#  skip_cleanup: true
#  local_dir: frontend/build/
#  github-token: $GITHUB_TOKEN # Set in the settings page of your repository, as a secure variable
#  on:
#    branch: master
