services: 
  - docker

before_install:
  - npm install -g cypress

script:
  - docker-compose -f docker-compose.prod.yml up -d 
  - cypress run --project ./frontend
  # Stop all processes to be able to bind to ports for specific unit tests
  - docker-compose down 
  # Run the backend tests
  - docker-compose -f docker-compose.prod.yml run backend npm test
  # Copy over the files to the container
  - docker-compose -f docker-compose.prod.yml run -v ${PWD}/new_build:/var/www/app/mnt frontend /bin/sh copy_files.sh
env: TZ=America/Chicago

after_success:
  - docker-compose run backend npm run test && npm run coverage

deploy:
  - provider: pages
    verbose: true
    skip_cleanup: true
    local_dir: new_build/
    github-token: $GITHUB_TOKEN
    on:
      branch: master
  # backend deploy
  - provider: script
    script: sh backend/deploy_heroku.sh
