name: Testing

on: [push]

jobs:
  # tests:
  #   name: Cypress Tests
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v1

  #     - name: Build Docker Image 📦
  #       run: docker-compose -f docker-compose.prod.yml build
  #       env:
  #         CUMTD_API_KEY: ${{ secrets.CUMTD_API_KEY }}

  #     - name: Set Timezone ⏱️
  #       uses: zcong1993/setup-timezone@master
  #       with:
  #         timezone: 'America/Chicago'

  #     - name: Backend Testing 🧪
  #       run: |
  #         ci_env=`bash <(curl -s https://codecov.io/env)`
  #         docker-compose run $ci_env backend npm run coverage
  #       env:
  #         CUMTD_API_KEY: ${{ secrets.CUMTD_API_KEY }}

  #     - name: Cypress Run 🌲
  #       uses: cypress-io/github-action@v2
  #       with:
  #         working-directory: frontend
  #         wait-on: 'http://localhost:3000'
  #         wait-on-timeout: 180
  #         start: docker-compose -f ../docker-compose.prod.yml up -d
  #       env:
  #         CUMTD_API_KEY: ${{ secrets.CUMTD_API_KEY }}

  #     - name: Stop Processes ✋
  #       run: docker-compose down -v

  #     - name: Copy Files
  #       run: docker-compose -f docker-compose.prod.yml run -v ${PWD}/new_build:/var/www/app/mnt frontend /bin/sh copy_files.sh

  deploy:
    runs-on: ubuntu-latest
    # needs: tests
    if: success()
    steps:
      - uses: actions/checkout@v1
      - uses: webfactory/ssh-agent@v0.5.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Deploy
        run: |
          ssh-keyscan -t rsa api.uiucbus.com >> ~/.ssh/known_hosts
          git remote add dokku dokku@api.uiucbus.com:api.uiucbus.com 
        env:
          SSH_HOST_KEY: ${{ secrets.SSH_HOST_KEY }}
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
